---
title: "Test Runs"
output:
  html_document:
    df_print: paged
---

## Test runs

This notebook prints out the scale tables for the Wilson combination product
sets commonly encountered in online archives, for example Scala. I use it to
check that the ratios match those scales.

```{r}
library(magrittr)

```

## Hexanies

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 7), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 9), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 7, 9), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 7, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 7, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 9, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 9, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 11, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

## Dekanies

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 7, 9), choose = 2)[["scale_table"]] %>%
  knitr::kable()


```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 7, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 7, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 9, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 9, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 11, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 7, 9, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 3, 9, 11, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 5, 7, 9, 11), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

```{r}
eikosany::scale_table(harmonics = c(1, 7, 9, 11, 13), choose = 2)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *

## Eikosany

```{r}
eikosany::scale_table(harmonics = c(1, 3, 5, 7, 9, 11), choose = 3)[["scale_table"]] %>%
  knitr::kable()

```
* * * * *
