---
output: github_document
bibliography: vignettes/REFERENCES.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# eikosany - Algorithmic Composition With Erv Wilson's Combination Product Sets

## Overview

`eikosany` is an R package of tools for algorithmic composition with Erv
Wilson's Combination Product Sets [@narushima2019microtonality, chapter 6].
It's meant to ***complement*** other microtonal composition tools, not
replace any of them.

About the name: an _Eikosany_ is a 20-note scale derived by Erv Wilson from
six harmonic factors. Although any six factors can be used, the most 
commonly encountered Eikosany uses the first six odd numbers: 1, 3, 5,
7, 9 and 11.

## Other tools

- [Scala](https://www.huygens-fokker.org/scala/). Note: this is ***not***
the Scala multi-paradigm programming language that runs on the Java Virtual
Machine. This is a specialized tool for working with musical scales.
- [Sevish's Scale Workshop](https://sevish.com/scaleworkshop/guide.htm).
This is a web-based tool for working with musical scales.
- [Leimma and Apotome](https://isartum.net/). These tools, by
[Khyam Allami](https://khyamallami.com/) and
[Counterpoint](https://ctpt.co/), are browser-based applications for
creating microtonal scales and making generative music with them.
- [ODDSound MTS-ESP](https://oddsound.com/mtsespsuite.php).
This is a plugin for digital audio workstations (DAWs) that facilitates
production of microtonal music. I own a copy and if you're making microtonal
electronic music, you should too. The Eikosany and other scales Erv Wilson
developed all ship with MTS-ESP, so you don't really need my R package to
compose with them.
- [Entonal Studio](https://entonal.studio/). Entonal Studio is a user
interface package for microtonal composition. It can operate as a
standalone application, a plugin host or a plugin. I own a copy of Entonal
Studio and recommend it highly.
- [Infinitone DMT](https://infinitone.com/). From the
[Infinitone DMT FAQ](https://infinitone.com/support/#faq-container):
"Infinitone DMT is a DAW plugin and standalone that empowers musicians to
easily use micro-tuning within their own workflow. ...

    "As a plugin, Infinitone DMT is inserted in your DAW as a MIDI effect.
    ... The standalone can be used separately from a DAW, or it can be used
    in conjunction with a DAW by routing MIDI data from the DAW to the
    standalone (and back)."
- [Universal Tuning Editor](https://hpi.zentral.zone/ute). Universal Tuning
Editor is an application for computing and visualizing microtonal scales and
tunings, and includes tools to interface with hardware and software
synthesizers.
- [Wilsonic](https://apps.apple.com/us/app/wilsonic/id848852071). This is a
free app that runs on iOS devices. I don't have any iOS devices so I've
never used this.

    There is also a version of Wilsonic in development for use with ODDSound
    MTS-ESP. See <https://wilsonic.co/downloads/downloads-mts-esp/> for the
    details.

- [Surge XT](https://surge-synthesizer.github.io/). Surge XT is an open source
full featured software synthesizer. The Surge XT community has invested a
significant level of effort into supporting alternate tuning systems.

See the [Xenharmonic Wiki List of microtonal software
plugins](https://en.xen.wiki/w/List_of_microtonal_software_plugins) for
more ways of making microtonal music.    

## Some history

On February 4, 2001, composer Iannis Xenakis passed away. I've been a fan of
experimental music, especially _musique concrète_, algorithmically composed
music, microtonal music, and other _avant-garde_ genres since I was an
undergraduate. Xenakis was one of the major figures in algorithmic
composition.

Reading the first edition of _Tuning, Timbre, Spectrum, Scale_
^[@sethares1998tuning] rekindled my appreciation for the microtonal music of
Harry Partch. And so, armed with copies of @sethares1998tuning,
_Formalized Music_ ^[@xenakis1992formalized], and _Genesis of a Music_
^[@partch1979genesis], I embarked on a path that led to
_When Harry Met Iannis_ ^[@Borasky2021a].

_When Harry Met Iannis_ was premiered at a microtonal music festival in El
Paso, Texas in late October, 2001. The [Bandcamp
version](https://algocompsynth.bandcamp.com/album/when-harry-met-iannis)
is essentially identical to that version; the source code is on GitHub at
<https://github.com/AlgoCompSynth/when-harry-met-iannis>.

At the festival, I met a number of composers who were working in microtonal
and just intonation, and one name kept coming up: Erv Wilson. Wilson was a
theoretician who developed keyboards, scales and tuning systems that
several composers were using at the time, and are still using today. Terumi
Narushima's _Microtonality and the Tuning Systems of Erv Wilson_
^[@narushima2019microtonality] is a comprehensive documentation of Wilson's
work and is the basis for much of the code in this package.

## Motivation

I have two main motivations:

1. There's an old saying that if you really want to learn something, teach a
computer to do it. In the case of Erv Wilson's musical constructs, teasing
the construction processes out of his and others' writings on the subject is
a non-trivial task.

    For example, much of Wilson's work consists of multi-dimensional graph
    structures drawn on flat paper. He did build physical three-dimensional
    models of some of them, but some can't even be rendered in three
    dimensions. And the graph theory operations that generated them and
    musical ways to traverse them are not at all obvious. 

2. The 20th anniversary of Xenakis' passing and of _When Harry Met Iannis_
occured in my second year of virtual isolation because of COVID-19. During
2021, I acquired two synthesizers that are capable of mapping the keyboards
to arbitrary microtonal scales: an [Ashun Sound Machines Hydrasynth
Desktop](https://www.ashunsoundmachines.com/hydrasynth-desk), and a [Korg
Minilogue XD](https://www.korg.com/us/products/synthesizers/minilogue_xd/).

    The Hydrasynth ships with the tuning tables for many of Erv Wilson's 
    scales already in the firmware. For the Minilogue XD, the user can
    load up to six custom scales with a software librarian program.
    
    But I'm not a keyboard player, and even if I were, the remapping
    process for the scales leaves only middle C where a musician would
    normally expect to find it. All the other notes are somewhere else.
    
    So I need a translator for the music I want to write that doesn't
    involve a lot of trial and error fumbling around on a remapped
    synthesizer or on-screen keyboard. CPS scales are aimed at harmonic
    musical structures like chords, and finding them on a remapped
    keyboard is tedious and error-prone.

    Music composed using Wilson's musical structures is mostly played on
    instruments custom-built for them. There are keyboards designed for
    Wilson's and other microtonal music; indeed, Wilson himself designed
    microtonal keyboards [@narushima2019microtonality, chapter 2]. But
    they're quite expensive and, like the instruments, custom-built. I need
    tools to work with what I have.

## References
