---
title: "Constructing the Eikosany"
output: rmarkdown::html_vignette
bibliography: eikosany.bibtex
vignette: >
  %\VignetteIndexEntry{Constructing the Eikosany}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eikosany)
```

## Computing Combination Product Set scales

```{r}

# the defaults yield the 1-3-5-7-9-11 Eikosany
eikosany <- scale_table()
knitr::kable(eikosany[["scale_table"]], digits = 2)

# the 1-3-5-7 Hexany
hexany_harmonics <- c(1, 3, 5, 7)
hexany_choose <- 2
hexany_1_3_5_7 <-
  scale_table(hexany_harmonics, hexany_choose)
knitr::kable(hexany_1_3_5_7[["scale_table"]], digits = 2)
knitr::kable(hexany_1_3_5_7[["interval_matrix"]], digits = 2)

# the 1-7-9-11-13 Dekany
dekany_harmonics <- c(1, 7, 9, 11, 13)
dekany_choose <- 2
dekany_1_7_9_11_13 <-
  scale_table(dekany_harmonics, dekany_choose)
knitr::kable(dekany_1_7_9_11_13[["scale_table"]], digits = 2)
knitr::kable(dekany_1_7_9_11_13[["interval_matrix"]])

# We might want to print out sheet music for a conventional keyboard
# player, since the synthesizer is mapping MIDI note numbers to pitches.
# We assume at least a 37-key synthesizer with middle C on the left.
# so the largest CPS scale we can play is a 35-note "35-any", made from
# seven harmonics taken three at a time.
harmonics_35 <- c(1, 3, 5, 7, 9, 11, 13)
choose_35 <- 3
any_35 <-
  scale_table(harmonics_35, choose_35)
knitr::kable(any_35[["scale_table"]], digits = 2)

```

## Computing chords - the tetrads of the 1-3-5-7-9-11 Eikosany

```{r}
# the defaults yield the 1-3-5-7-9-11 Eikosany
eikosany_scale <- scale_table()[["scale_table"]]
knitr::kable(eikosany_scale, digits = 2)

# the defaults yield the tetrads of the 1-3-5-7-9-11 Eikosany
eikosany_chords <- chord_table(eikosany_scale)
knitr::kable(eikosany_chords, digits = 2)

```

## References
