---
title: "Run the Examples"
output: rmarkdown::html_vignette
bibliography: eikosany.bibtex
vignette: >
  %\VignetteIndexEntry{Run the Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eikosany)
```

This vignette just runs the examples. See @narushima2019microtonality for the
details.

## create_cps_scale_table examples
```{r}

# 12EDO scale table
print(vanilla <- create_12edo_scale_table())

# the defaults yield the 1-3-5-7-9-11 Eikosany
print(eikosany <- create_cps_scale_table())

# the 1-3-5-7 Hexany
hexany_harmonics <- c(1, 3, 5, 7)
hexany_choose = 2
print(hexany <- create_cps_scale_table(hexany_harmonics, hexany_choose))

# the 1-7-9-11-13 2)5 Dekany
dekany_harmonics <- c(1, 7, 9, 11, 13)
dekany_choose <- 2
print(dekany <- create_cps_scale_table(dekany_harmonics, dekany_choose))

# We might want to print out sheet music for a conventional keyboard
# player, since the synthesizer is mapping MIDI note numbers to pitches.
# We assume at least a 37-key synthesizer with middle C on the left,
# so the largest CPS scale we can play is a 35-note "35-any", made from
# seven harmonics taken three at a time.
harmonics_35 <- c(1, 3, 5, 7, 9, 11, 13)
choose_35 <- 3
print(any_35 <- create_cps_scale_table(harmonics_35, choose_35))

```

## Interval table example
```{r}
print(eikosany_interval_table <-create_interval_table(eikosany))

```

## Chord table examples
```{r}

# compute the tetrads of the 1-3-5-7-9-11 Eikosany
eikosany <- create_cps_scale_table()
print(eikosany_chords <- create_chord_table(eikosany))

# compute the pentads of the 1-3-5-7-9-11-13-15 Hebdomekontany
hebdomekontany <- create_cps_scale_table(
  harmonics = c(1, 3, 5, 7, 9, 11, 13, 15), choose = 4
)
print(hebdomekontany_chords <- create_chord_table(hebdomekontany))

```

## Keyboard map examples
```{r}
hexany <- create_cps_scale_table(hexany_harmonics, hexany_choose)
print(hexany_keyboard_map <- create_keyboard_map(hexany))
print(dekany_keyboard_map <- create_keyboard_map(dekany))
print(vanilla_keyboard_map <- create_keyboard_map(vanilla))
print(eikosany_keyboard_map_c3 <-
  create_keyboard_map(eikosany, middle_c_octave = 3)
)

```

## Minilogue XD `.scl` file example
```{r}
print(eikosany_minilogue_xd_scl_file <- create_minilogue_xd_scale_file(
  eikosany_keyboard_map_c3,
  "~/Eikosany-1-3-5-7-9-11.scl",
  "Eikosany 1-3-5-7-9-11"
))
```

## References
