---
title: "Tetrads of the 1-3-5-7-9-11 Eikosany on a 37-key Synthesizer"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eikosany)
```

## The scale table
```{r}
scale <- cps_scale_table(root_divisor = 33) # 1-3-5-7-9-11 Eikosany default
print(scale)

```

## The keyboard map
```{r}
map <- keyboard_map(scale)
print(map)

```

## The chord table
```{r}
chords <- cps_chord_table(scale)
print(chords)

```

## The plots
```{r fig.width=11, fig.height=4.25}
scale_degrees <- length(scale$degree) - 1
base_note_number = 48
chord_names <- chords$chord
degrees <- chords$degrees
degrees_matrix <- matrix(
  unlist(lapply(strsplit(degrees, ":"), as.numeric)),
  byrow = TRUE,
  nrow = length(degrees)
)

for (ichord in 1:nrow(degrees_matrix)) {
  chord_vector <- degrees_matrix[ichord, ]
  title_string <- paste(
    "Chord =",
    chord_names[ichord],
    ", Degrees =",
    degrees[ichord],
    ", Base C =",
    base_note_number,
    ", Scale degrees =",
    scale_degrees,
    sep = " "
  )
  piano_plot <- chord_plot(
    chord_vector, title_string, map, base_note_number
  )
  print(piano_plot)
}

```
