#' @title xen.assist - Shiny app for xentonal composition via chat
#'
#' @description Launches a two-pane Shiny app: left/main pane runs the `btw`-enhanced chat,
#' right/sidebar pane holds an audio player that plays back the last WAV file
#' synthesized and a model picker to swap LLM models mid-session.
#' Uses Bootstrap 5 darkly theme per project conventions.
#'
#' @param client Configuration for the LLM client; passed through to
#'   `btw::btw_client()`. Supply a list or object compatible with your
#'   inference backend (e.g., Ollama). Defaults to `NULL`, which may use
#'   whatever defaults `btw` resolves.
#' @param tools Tools available to the agent. Character vector of tool names,
#'   or list of tool objects. Defaults to `c("env", "run", "files")`.
#' @param messages Initial message history as a list. Passed through to the
#'   chat module. Defaults to an empty list.
#'
#' @return A Shiny application object (generated by `shiny::shinyApp()`).
#'
#' @examples
#' \dontrun{
#'   # Start with default client and standard tools
#'   xen_chat()
#' }
#'
#' @importFrom ollamar list_models
#' @importFrom shiny addResourcePath tags selectizeInput uiOutput reactiveVal observeEvent showNotification renderUI shinyApp req
#' @importFrom bslib page_fillable layout_sidebar sidebar bs_theme
#' @importFrom shinychat chat_mod_ui chat_mod_server
#' @importFrom ellmer tool type_string
#' @importFrom btw btw_client
#' @export
xen_chat <- function(
  client   = NULL,
  tools    = c("env", "run", "files"),
  messages = list()
) {
  # ---- Model discovery via ollamar ---------------------------------

  # Discover available models through the ollamar R package (wraps Ollama API)
  model_df <- tryCatch(
    ollamar::list_models(),
    error = function(e) NULL
  )

  if (!is.null(model_df) && nrow(model_df) > 0L) {
    # Unique, sorted character vector of model names
    model_choices <- sort(unique(model_df[["name"]], na.rm = TRUE))
  } else {
    model_choices <- character(0)
  }

  # Determine default: prefer client$model if set, otherwise first available
  default_model <- if (!is.null(client[["model"]]) && nzchar(client[["model"]])) {
    client[["model"]]
  } else if (length(model_choices) > 0L) {
    model_choices[1]
  } else {
    NULL
  }

  # ---- Setup -----------------------------------------------------

  # Create a temporary directory for WAV files so synthesized output
  # is always available under the app-managed resource path.
  wav_dir <- file.path(tempdir(), "XentonalAssistant_wav")
  dir.create(wav_dir, recursive = TRUE, showWarnings = FALSE)

  # Register resource path so Shiny can serve WAV files to the browser
  shiny::addResourcePath("wav", wav_dir)

  # ---- UI ---------------------------------------------------------

  ui <- bslib::page_fillable(
    shiny::tags$h3("[Xen] xen.assist"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        width = 300,

        # -- Model picker section --
        shiny::tags$h4("[Model] LLM"),
        if (length(model_choices) > 0L) {
          shiny::selectizeInput(
            "model_picker",
            NULL,
            choices = model_choices,
            selected = default_model %||% model_choices[1],
            options = list(placeholder = "(choose a model)", create = FALSE),
            width = "100%"
          )
        } else {
          shiny::tags$p(style = "color: gray;", "No models detected.")
        },

        shiny::tags$hr(),

        # -- Audio player section --
        shiny::tags$h4("[Audio] Last synthesis"),
        shiny::uiOutput("audio_panel"),
        shiny::tags$hr(),
        shiny::tags$p("The agent can synthesize xentonal scales and chords using the 'eikosany' package."),
        shiny::tags$p("Request a WAV file to hear the result here.")
      ),

      # The chat interface is the main content of layout_sidebar
      shinychat::chat_mod_ui(
        "chat",
        messages = if (length(messages) == 0) NULL else messages
      )
    ),
    theme = bslib::bs_theme(bootswatch = "darkly")
  )

  # ---- SERVER -----------------------------------------------------

  server <- function(input, output, session) {

    # Reactive value to store the path to the last synthesized WAV file
    r_last_wav <- shiny::reactiveVal(NULL)

    # Tool for the agent to notify the UI about a new WAV file.
    # Critical fix: copy the synthesized file into wav_dir so the
    # Shiny resource path can actually serve it.
    update_wav_tool <- ellmer::tool(
      fun = function(path) {
        # Validate: must be a non-empty character string
        if (!is.character(path) || length(path) != 1L || !nzchar(path)) {
          return("Error: path must be a non-empty file path string.")
        }

        # Resolve to absolute path; don't fail if it doesn't exist yet
        abs_path <- normalizePath(path, mustWork = FALSE)

        # Copy the WAV file into wav_dir so Shiny can serve it via
        # our registered resource path.
        dest_file <- file.path(wav_dir, basename(abs_path))
        ok <- tryCatch(
          {
            file.copy(abs_path, dest_file, overwrite = TRUE)
          },
          error = function(e) FALSE
        )

        if (!ok || !file.exists(dest_file)) {
          return(paste("Error: could not serve WAV file at path:", abs_path))
        }

        r_last_wav(dest_file)
        paste("Audio player updated to play:", basename(dest_file))
      },
      description = "Sets the audio player to play the specified WAV file. Call this immediately after synthesizing and saving a WAV file.",
      name = "set_audio_player",
      arguments = list(
        path = ellmer::type_string("The absolute or relative filesystem path to the synthesized WAV file.")
      )
    )

    # Merge custom tool with user-supplied tools
    full_tools <- tools
    if (is.character(full_tools)) {
      full_tools <- c(full_tools, list(update_wav_tool))
    } else {
      full_tools <- append(full_tools, list(update_wav_tool))
    }

    # Build initial btw client
    initial_client <- btw::btw_client(client = client, tools = full_tools)

    # Remember the provider so we can rebuild on swap when `client` was NULL.
    # ellmer's $get_provider() returns an R6 Provider object (not a string),
    # so we prefer the explicit config field; default to "ollama" since
    # ollamar only works with Ollama endpoints anyway.
    provider_name <- if (is.list(client) && !is.null(client[["provider"]])) {
      client[["provider"]]
    } else {
      "ollama"
    }

    # Instantiate the chat server -- returns an env with $set_client()
    chat_server <- shinychat::chat_mod_server(
      "chat",
      client = initial_client
    )

    # ---- Model picker: reactively swap the client -----------------------

    shiny::observeEvent(input$model_picker, label = "model_swap", {
      req(length(model_choices) > 0L)

      new_model <- input$model_picker

      # Build a fresh btw-configured ellmer Chat with the chosen model.
      # We reuse the original client config, overriding only the model field.
      new_client_config <- client
      if (is.null(new_client_config)) {
        new_client_config <- list(provider = provider_name)
      }
      new_client_config[["model"]] <- new_model

      new_ellmer_chat <- tryCatch(
        btw::btw_client(client = new_client_config, tools = full_tools),
        error = function(e) NULL
      )

      if (is.null(new_ellmer_chat)) {
        shiny::showNotification(
          paste("Could not switch model: could not create client."),
          type = "error",
          duration = 5
        )
        return()
      }

      # Use shinychat's built-in $set_client() which handles:
      #   - copying history, system prompt, tools onto the new client
      #   - pending-swapping if a stream is currently running
      chat_server$set_client(new_ellmer_chat, sync = TRUE)

      shiny::showNotification(
        paste0("Switched to ", new_model),
        type = "message",
        duration = 3
      )
    })

    # ---- Audio panel ----------------------------------------------------

    output$audio_panel <- shiny::renderUI({
      wav_path <- r_last_wav()
      if (is.null(wav_path) || !file.exists(wav_path)) {
        shiny::tags$p("No synthesis yet.")
      } else {
        rel_name <- basename(wav_path)
        shiny::tags$div(
          class = "text-center",
          shiny::tags$audio(
            src      = paste0("wav/", rel_name),
            controls = TRUE,
            style    = "width: 100%"
          ),
          shiny::tags$p(paste("File:", rel_name), style = "font-size: 0.8rem; color: gray;")
        )
      }
    })
  }

  # ---- LAUNCH -----------------------------------------------------

  shiny::shinyApp(ui, server)
}
